# Generated by Django 5.1.2 on 2024-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_imgs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
