# Generated by Django 5.1.2 on 2024-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_course_featured_img_course_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
