# Generated by Django 5.1.2 on 2024-11-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_student_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='confirm_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
